
%% Parameters
mb = 300; mw = 60;
ks = 16000; kt = 190000;
bs = 1000; delta_k = 0.1; delta_b = 0.1;
ks_nl = 5000; x_eq = 0.05;

ks_eq = ks
bs_eq = bs

%% State-space model
A = [0 0 1 0;
     0 0 0 1;
     -ks/mb -ks/mb -bs/mb bs/mb;
      ks_eq/mw -(ks_eq+kt)/mw bs_eq/mw -bs_eq/mw];

B = [0 0;
     0 0;
     1/mb 0;
    -1/mw kt/mw];

Bf = B(:,1);    % actuator input
Br = B(:,2);    % road disturbance input

C = [1 0 0 0;
     0 1 0 0];  % Measured outputs (x_b, x_w)
D = [0 0; 0 0];

%% Pole placement controller
desired_poles = [-5 -6 -8 -10];
K = place(A, Bf, desired_poles);

%% Observer Design (Luenberger)
observer_poles = [-20 -25 -30 -35];  % Faster than controller poles
L = place(A.', C.', observer_poles)';

%% Road disturbance signal
Ar = 0.01;             % amplitude (meters)
wr = 8;                % frequency (rad/s)
r = @(t) Ar * sin(wr*t);

%% Initial Conditions
x0 = [0.01; 0.005; 0; 0];           % True state
xhat0 = [0.01; 0.01; 0; 0];  % Estimated state guess
z0 = [x0; xhat0];            % Combined state vector

%% Combined Dynamics: True System + Observer
% z = [x; xhat]
dxdt = @(t,z) [
    A*z(1:4) + Bf*(-K*z(5:8));  % True state dynamics
    A*z(5:8) + Bf*(-K*z(5:8)) + L*(C*z(1:4) - C*z(5:8))  % Observer
];

%% Simulate system
tspan = 0:0.01:10;
[t, z] = ode45(dxdt, tspan, z0);

x = z(:,1:4);     % True state
xhat = z(:,5:8);  % Estimated state

%% Plot True vs Estimated State
figure;
subplot(2,1,1);
plot(t, x(:,1), 'b', t, xhat(:,1), 'r--', 'LineWidth', 1.5);
legend('x_b (true)', 'x_b (est)');
ylabel('x_b (m)'); title('Body Displacement Estimation');

subplot(2,1,2);
plot(t, x(:,3), 'b', t, xhat(:,3), 'r--', 'LineWidth', 1.5);
legend('v_b (true)', 'v_b (est)');
ylabel('Velocity (m/s)'); xlabel('Time (s)');
title('Body Velocity Estimation');

%% Plot Displacement Response
figure;
plot(t, x(:,1), 'b', t, x(:,2), 'r--', 'LineWidth', 1.5);
xlabel('Time (s)'); ylabel('Displacement (m)');
legend('x_b (Body)', 'x_w (Wheel)');
title('System Response with Observer and Road Disturbance');

%% Plot Control Effort
u = - (xhat * K')';  % Control input from estimated state

figure;
plot(t, u, 'k', 'LineWidth', 1.5);
xlabel('Time (s)');
ylabel('Control Effort f_s (N)');
title('Control Effort Generated by Observer-Based Controller');

%% (1) Simulate with Controller (same as before)
dxdt_controller = @(t,x) (A - Bf*K)*x ;
[t1, x1] = ode45(dxdt_controller, t, x0);  % Closed-loop

%% (2) Simulate without Controller (open-loop system)
dxdt_openloop = @(t,x) A*x ;  
[t2, x2] = ode45(dxdt_openloop, t, x0);    % Open-loop

%% Plot Comparison: Body Displacement
figure;
plot(t1, x1(:,1), 'b', 'LineWidth', 1.8); hold on;
plot(t2, x2(:,1), 'r--', 'LineWidth', 1.8);
xlabel('Time (s)');
ylabel('Body Displacement x_b (m)');
legend('With Controller', 'Without Controller');
title('Effect of Controller on Body Stabilization');
grid on;